/** German names of the track pieces for the editor (module name → label). */
export const PIECE_NAMES: Record<string, string> = {
  canopy: 'Baumkronen',
  'vine-swing': 'Lianen-Sägen',
  temple: 'Tempeldach',
  'pad-grove': 'Pilzhain',
  ruins: 'Ruinen',
  waterfall: 'Wasserfall',
  chimney: 'Kletterkamin',
  rails: 'Schienen',
  shaft: 'Schacht',
  'crusher-hall': 'Stampferhalle',
  'gear-lift': 'Zahnrad-Aufzug',
  scaffold: 'Gerüst',
  minecart: 'Lorenbahn',
  collapse: 'Einsturz',
  islands: 'Inselkette',
  updraft: 'Aufwind',
  'crumble-bridge': 'Bröckelbrücke',
  'mega-bounce': 'Mega-Sprung',
  arches: 'Wolkenbögen',
  'cloud-hop': 'Wolkenhüpfer',
  'windy-ridge': 'Windkamm',
  rooftops: 'Dächer',
  'laser-hall': 'Laserhalle',
  elevators: 'Aufzüge',
  'boost-highway': 'Turbo-Highway',
  billboard: 'Werbetafel',
  'hover-pads': 'Schwebeplatten',
  monorail: 'Einschienenbahn',
  'flooded-hall': 'Geflutete Halle',
  current: 'Strömung',
  'bubble-lift': 'Blasenlift',
  'sunken-columns': 'Säulen',
  reef: 'Riff',
  'air-pocket': 'Luftblase',
  decks: 'Schiffsdecks',
  'cannon-deck': 'Kanonendeck',
  rigging: 'Takelage',
  'plank-walk': 'Planke',
  'balloon-lift': 'Ballonlift',
  broadside: 'Breitseite',
  dunes: 'Dünen',
  pyramid: 'Pyramide',
  quicksand: 'Treibsand',
  sandstorm: 'Sandsturm',
  'cactus-field': 'Kaktusfeld',
  obelisks: 'Obelisken',
  'bounce-garden': 'Hüpfgarten',
  'crystal-cave': 'Kristallhöhle',
  'spore-lift': 'Sporenlift',
  'shroom-bridges': 'Pilzbrücken',
  'glow-maze': 'Leuchtlabyrinth',
  pendulums: 'Pendel',
};

export function pieceName(name: string): string {
  return PIECE_NAMES[name] ?? name;
}
